version: '3.9'

services:
  daw:
    container_name: daw
    build:
      context: .
      target: runtime
    volumes:
      - daw-sqlite:/data/sqlite
    privileged: true
    ports: 
      - 8080:8080
    restart: unless-stopped
    networks: 
      - daw-network

networks:
  daw-network:
    name: daw-network

volumes:
  daw-sqlite:
    name: daw-sqlite